quizData.listening[500] = [
  {"sentence": "A: All visitors must check in at reception.\nB: Got it.", "translation": "", "q": "What must visitors do?", "choices": ["Check in", "Pay", "Sign out", "Call first"], "answer": "Check in", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: This training is mandatory.\nB: So everyone has to attend.", "translation": "", "q": "What does B mean?", "choices": ["Only managers attend", "No one attends", "Everyone attends", "It's optional"], "answer": "Everyone attends", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The package was damaged in transit.\nB: We should request an exchange.", "translation": "", "q": "What will they request?", "choices": ["A discount", "An exchange", "A promotion", "A meeting"], "answer": "An exchange", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The new policy takes effect next month.\nB: We should inform the staff.", "translation": "", "q": "What should they do?", "choices": ["Inform staff", "Cancel training", "Increase prices", "Move offices"], "answer": "Inform staff", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please submit your expense report by Friday.\nB: I'll do it this afternoon.", "translation": "", "q": "When will B submit it?", "choices": ["This afternoon", "Friday night", "Next week", "Tomorrow"], "answer": "This afternoon", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The supplier agreed to reduce the price.\nB: That's great news.", "translation": "", "q": "What did the supplier agree to do?", "choices": ["Increase price", "Reduce price", "Delay shipment", "Cancel contract"], "answer": "Reduce price", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The seminar was canceled due to bad weather.\nB: Let's reschedule it.", "translation": "", "q": "What will they do?", "choices": ["Hold it today", "Reschedule", "Refund tickets", "Move it online"], "answer": "Reschedule", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We will notify you as soon as we have an update.\nB: Thanks for letting me know.", "translation": "", "q": "What will A do later?", "choices": ["Send an update", "Cancel the order", "Visit the office", "Call the supplier"], "answer": "Send an update", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The product comes with a one-year warranty.\nB: Good, that's important.", "translation": "", "q": "What does the product include?", "choices": ["A discount", "A warranty", "A receipt", "A refund"], "answer": "A warranty", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We're looking forward to your reply.\nB: I'll respond soon.", "translation": "", "q": "What will B do?", "choices": ["Reply soon", "Cancel", "Send a refund", "Schedule a call"], "answer": "Reply soon", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please transfer the call to Mr. Kim.\nB: One moment.", "translation": "", "q": "What will B do?", "choices": ["End the call", "Transfer it", "Ignore it", "Take a message"], "answer": "Transfer it", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The survey results were useful.\nB: Let's share them with the team.", "translation": "", "q": "What will they share?", "choices": ["The survey results", "The invoice", "The schedule", "The contract"], "answer": "The survey results", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The office will be closed for a holiday.\nB: Then we can't meet there.", "translation": "", "q": "Why can't they meet?", "choices": ["No room", "Holiday closure", "Bad weather", "Late shipment"], "answer": "Holiday closure", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The contract was signed by both parties.\nB: Great, we can start.", "translation": "", "q": "What happened?", "choices": ["They canceled", "They signed", "They delayed", "They negotiated"], "answer": "They signed", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please follow the procedure.\nB: Sure, step by step.", "translation": "", "q": "What will B do?", "choices": ["Follow the procedure", "Skip steps", "Change rules", "Ask customers"], "answer": "Follow the procedure", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"}
];
