quizData.listening[600] = [
  {"sentence": "A: The delivery was delayed due to traffic.\nB: Can we still meet the deadline?", "translation": "", "q": "What is B concerned about?", "choices": ["The price", "The deadline", "The warranty", "The survey"], "answer": "The deadline", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please keep this information confidential.\nB: Understood.", "translation": "", "q": "What does A ask B to do?", "choices": ["Share it", "Keep it confidential", "Print it", "Publish it"], "answer": "Keep it confidential", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The attachment contains the updated contract.\nB: I'll review it now.", "translation": "", "q": "What will B do?", "choices": ["Sign it immediately", "Review it", "Delete it", "Forward it to customers"], "answer": "Review it", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We need to implement the new system by June.\nB: Let's make a plan.", "translation": "", "q": "By when must they implement it?", "choices": ["May", "June", "July", "August"], "answer": "June", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Customers can file a complaint online.\nB: That will save time.", "translation": "", "q": "How can customers file a complaint?", "choices": ["By phone", "Online", "In person only", "By mail"], "answer": "Online", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Are we eligible for the program?\nB: Yes, since we meet the requirements.", "translation": "", "q": "Why are they eligible?", "choices": ["They paid a fee", "They meet requirements", "They are new", "They are late"], "answer": "They meet requirements", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We recommend registering early.\nB: OK, I'll sign up today.", "translation": "", "q": "What does A recommend?", "choices": ["Registering early", "Canceling", "Waiting", "Calling"], "answer": "Registering early", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The supplier will ship the parts next week.\nB: Then we can start assembly.", "translation": "", "q": "When will the parts be shipped?", "choices": ["This week", "Next week", "Tomorrow", "Next month"], "answer": "Next week", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The team discussed ways to improve efficiency.\nB: We should automate some steps.", "translation": "", "q": "What is the goal?", "choices": ["Improve efficiency", "Hire staff", "Cut salaries", "Move offices"], "answer": "Improve efficiency", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The contract will be renewed automatically.\nB: So we don't need to sign again.", "translation": "", "q": "What does B mean?", "choices": ["They must re-sign", "No need to sign again", "The contract ends", "They must negotiate"], "answer": "No need to sign again", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The item is out of stock.\nB: When will it be available?", "translation": "", "q": "What does B want to know?", "choices": ["The price", "Availability date", "Store location", "Refund policy"], "answer": "Availability date", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The director approved the budget proposal.\nB: Great, we can move forward.", "translation": "", "q": "What was approved?", "choices": ["A schedule", "A budget proposal", "A complaint", "A shipment"], "answer": "A budget proposal", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please submit the application online.\nB: I'll do it after the meeting.", "translation": "", "q": "How will B submit it?", "choices": ["By mail", "Online", "In person", "By fax"], "answer": "Online", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We will announce the new policy tomorrow.\nB: I'll tell the team.", "translation": "", "q": "When will the policy be announced?", "choices": ["Today", "Tomorrow", "Next week", "Next month"], "answer": "Tomorrow", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The maintenance will start at 9 p.m.\nB: Then the system may be unavailable.", "translation": "", "q": "When will maintenance start?", "choices": ["9 a.m.", "9 p.m.", "10 p.m.", "Midnight"], "answer": "9 p.m.", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"}
];
