quizData.listening[400] = [
  {"sentence": "A: Could we reschedule the appointment?\nB: Sure, how about Thursday morning?", "translation": "", "q": "What does B suggest?", "choices": ["Canceling", "Moving it to Thursday morning", "Keeping the time", "Meeting today"], "answer": "Moving it to Thursday morning", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The invoice is due tomorrow.\nB: Then we should pay today.", "translation": "", "q": "What will they do today?", "choices": ["Send a complaint", "Pay the invoice", "Place an order", "Request a refund"], "answer": "Pay the invoice", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please attach the receipt.\nB: I'll add it to the email.", "translation": "", "q": "What will B attach?", "choices": ["A schedule", "A receipt", "A contract", "A photo"], "answer": "A receipt", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The conference room is not available.\nB: Let's use Room 204.", "translation": "", "q": "What will they do?", "choices": ["Wait", "Use Room 204", "Cancel the meeting", "Move to the lobby"], "answer": "Use Room 204", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Is there a discount for members?\nB: Yes, ten percent.", "translation": "", "q": "How much is the discount?", "choices": ["5%", "10%", "15%", "20%"], "answer": "10%", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The printer isn't working.\nB: I'll call the IT desk.", "translation": "", "q": "What will B do?", "choices": ["Buy a new printer", "Call IT", "Ignore it", "Print later"], "answer": "Call IT", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Did you submit the form?\nB: Not yet, I'll do it now.", "translation": "", "q": "What will B do now?", "choices": ["Submit the form", "Cancel the form", "Review the report", "Call the manager"], "answer": "Submit the form", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Your order will be shipped on Friday.\nB: Great, thank you.", "translation": "", "q": "When will the order be shipped?", "choices": ["Thursday", "Friday", "Saturday", "Sunday"], "answer": "Friday", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Where is the reception desk?\nB: It's next to the elevator.", "translation": "", "q": "Where is the desk?", "choices": ["By the stairs", "Next to the elevator", "In the cafeteria", "Outside"], "answer": "Next to the elevator", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Could you send the update to the team?\nB: Sure, I'll message them.", "translation": "", "q": "Who will receive the update?", "choices": ["Customers", "The team", "A supplier", "No one"], "answer": "The team", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The deadline is next Monday.\nB: We need to finish this week.", "translation": "", "q": "When do they need to finish?", "choices": ["Next month", "This week", "Next week", "Tomorrow"], "answer": "This week", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Do you have any questions?\nB: Yes, about the schedule.", "translation": "", "q": "What is B asking about?", "choices": ["The price", "The schedule", "The location", "The manager"], "answer": "The schedule", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The hotel reservation is confirmed.\nB: Perfect.", "translation": "", "q": "What is confirmed?", "choices": ["A meeting", "A reservation", "A shipment", "A refund"], "answer": "A reservation", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please wait in the lobby.\nB: OK.", "translation": "", "q": "Where should B wait?", "choices": ["In the lobby", "In the office", "In the elevator", "In the parking lot"], "answer": "In the lobby", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We received a customer complaint.\nB: Let's respond today.", "translation": "", "q": "What will they do today?", "choices": ["Ignore it", "Respond", "Refund immediately", "Close the store"], "answer": "Respond", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"}
];
