quizData.listening[900] = [
  {"sentence": "A: We need to scrutinize the contract before signing.\nB: Yes, especially the liability clause.", "translation": "", "q": "What are they focusing on?", "choices": ["The schedule", "The liability clause", "The office location", "The discount"], "answer": "The liability clause", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The auditor found a discrepancy in the records.\nB: We must rectify it immediately.", "translation": "", "q": "What will they do?", "choices": ["Ignore it", "Rectify the discrepancy", "Cancel the audit", "Increase prices"], "answer": "Rectify the discrepancy", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Let's mitigate the risk of delays.\nB: We can add a buffer in the timeline.", "translation": "", "q": "How will they mitigate risk?", "choices": ["Remove the deadline", "Add a buffer", "Cancel the project", "Skip testing"], "answer": "Add a buffer", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: This solution is viable only if costs drop.\nB: Then we should negotiate with suppliers.", "translation": "", "q": "Under what condition is it viable?", "choices": ["If costs drop", "If revenue drops", "If staff quit", "If rules change"], "answer": "If costs drop", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The policy will be amended next quarter.\nB: We'll update the handbook.", "translation": "", "q": "What will they update?", "choices": ["A menu", "A handbook", "A shipment label", "A logo"], "answer": "A handbook", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The new rule sets a precedent.\nB: Future cases will follow it.", "translation": "", "q": "What does B mean?", "choices": ["It's temporary", "It affects future cases", "It's optional", "It's private"], "answer": "It affects future cases", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Some departments are exempt from the requirement.\nB: So they don't need to comply.", "translation": "", "q": "What does exempt mean here?", "choices": ["They must comply", "They are excluded", "They are audited", "They are promoted"], "answer": "They are excluded", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: We plan to consolidate regional offices.\nB: That should reduce overhead.", "translation": "", "q": "Why consolidate?", "choices": ["To increase overhead", "To reduce overhead", "To add offices", "To delay work"], "answer": "To reduce overhead", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The committee must remain impartial.\nB: We should avoid conflicts of interest.", "translation": "", "q": "Why remain impartial?", "choices": ["To avoid conflicts of interest", "To speed delivery", "To raise prices", "To cut staff"], "answer": "To avoid conflicts of interest", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: This certification is a prerequisite for the role.\nB: Applicants must have it.", "translation": "", "q": "What is true?", "choices": ["It's optional", "Applicants must have it", "It's unrelated", "It's expired"], "answer": "Applicants must have it", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The regulations will be strictly enforced.\nB: Then we must comply fully.", "translation": "", "q": "What will happen to the regulations?", "choices": ["They'll be ignored", "They'll be enforced", "They'll be canceled", "They'll be delayed"], "answer": "They'll be enforced", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: Please ensure your report is pertinent to the topic.\nB: I'll remove unrelated details.", "translation": "", "q": "What will B remove?", "choices": ["Unrelated details", "All data", "The title", "The deadline"], "answer": "Unrelated details", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The director will oversee the project.\nB: Then we'll report to her weekly.", "translation": "", "q": "What will they do weekly?", "choices": ["Report to her", "Cancel meetings", "Audit expenses", "Change suppliers"], "answer": "Report to her", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The risk is negligible.\nB: Then we can proceed.", "translation": "", "q": "How big is the risk?", "choices": ["Large", "Negligible", "Unknown", "Growing"], "answer": "Negligible", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"},
  {"sentence": "A: The system is obsolete.\nB: We should replace it.", "translation": "", "q": "What should they do?", "choices": ["Keep it", "Replace it", "Advertise it", "Audit it"], "answer": "Replace it", "explanation": "英文の要点（日時・意図・指示など）に注目して選びましょう。"}
];
