quizData.vocabulary[500] = [
  {"q": "shipment", "choices": ["保証", "発送", "通知する", "配達"], "answer": "発送", "explanation": "'shipment' は『発送』を意味します。"},
  {"q": "delivery", "choices": ["配達", "返金", "必須の", "要求する"], "answer": "配達", "explanation": "'delivery' は『配達』を意味します。"},
  {"q": "refund", "choices": ["研修", "返金", "規定／方針", "調査"], "answer": "返金", "explanation": "'refund' は『返金』を意味します。"},
  {"q": "exchange", "choices": ["研修", "通知する", "交換", "出席する"], "answer": "交換", "explanation": "'exchange' は『交換』を意味します。"},
  {"q": "warranty", "choices": ["予定を変更する", "交換", "設備／機器", "保証"], "answer": "保証", "explanation": "'warranty' は『保証』を意味します。"},
  {"q": "policy", "choices": ["出席する", "要求する", "予定を変更する", "規定／方針"], "answer": "規定／方針", "explanation": "'policy' は『規定／方針』を意味します。"},
  {"q": "procedure", "choices": ["配達", "保証", "手順", "返金"], "answer": "手順", "explanation": "'procedure' は『手順』を意味します。"},
  {"q": "approve", "choices": ["承認する", "配達", "返金", "交換"], "answer": "承認する", "explanation": "'approve' は『承認する』を意味します。"},
  {"q": "reject", "choices": ["通知する", "却下する", "確認する", "配達"], "answer": "却下する", "explanation": "'reject' は『却下する』を意味します。"},
  {"q": "attend", "choices": ["出席する", "予定を変更する", "交換", "通知する"], "answer": "出席する", "explanation": "'attend' は『出席する』を意味します。"},
  {"q": "reschedule", "choices": ["通知する", "予定を変更する", "必須の", "発送"], "answer": "予定を変更する", "explanation": "'reschedule' は『予定を変更する』を意味します。"},
  {"q": "confirm", "choices": ["設備／機器", "通知する", "返金", "確認する"], "answer": "確認する", "explanation": "'confirm' は『確認する』を意味します。"},
  {"q": "notify", "choices": ["規定／方針", "予定を変更する", "手順", "通知する"], "answer": "通知する", "explanation": "'notify' は『通知する』を意味します。"},
  {"q": "provide", "choices": ["設備／機器", "研修", "承認する", "提供する"], "answer": "提供する", "explanation": "'provide' は『提供する』を意味します。"},
  {"q": "require", "choices": ["確認する", "要求する", "発送", "保証"], "answer": "要求する", "explanation": "'require' は『要求する』を意味します。"},
  {"q": "optional", "choices": ["保証", "研修", "返金", "任意の"], "answer": "任意の", "explanation": "'optional' は『任意の』を意味します。"},
  {"q": "mandatory", "choices": ["調査", "交換", "設備／機器", "必須の"], "answer": "必須の", "explanation": "'mandatory' は『必須の』を意味します。"},
  {"q": "equipment", "choices": ["交換", "設備／機器", "返金", "予定を変更する"], "answer": "設備／機器", "explanation": "'equipment' は『設備／機器』を意味します。"},
  {"q": "training", "choices": ["研修", "承認する", "予定を変更する", "確認する"], "answer": "研修", "explanation": "'training' は『研修』を意味します。"},
  {"q": "survey", "choices": ["配達", "任意の", "調査", "要求する"], "answer": "調査", "explanation": "'survey' は『調査』を意味します。"}
];
