if (!quizData) var quizData = {};
if (!quizData.vocabulary) quizData.vocabulary = {};

quizData.vocabulary[600] = [
  { "q": "available", "choices": ["高価な", "利用できる", "無料の", "予約済みの"], "answer": "利用できる", "explanation": "'available' は『利用できる』や『入手できる』を意味します。" },
  { "q": "conference", "choices": ["旅行", "会議", "報告書", "契約"], "answer": "会議", "explanation": "'conference' は『会議』、特に大規模なものを指します。" },
  { "q": "employee", "choices": ["顧客", "従業員", "経営者", "株主"], "answer": "従業員", "explanation": "'employee' は『従業員』を意味します。" },
  { "q": "discuss", "choices": ["決定する", "発表する", "議論する", "断る"], "answer": "議論する", "explanation": "'discuss' は『〜について議論する』を意味します。" },
  { "q": "department", "choices": ["部署", "会社", "建物", "市場"], "answer": "部署", "explanation": "'department' は『部署』や『部門』を意味します。" },
  { "q": "include", "choices": ["除く", "追加する", "含む", "変更する"], "answer": "含む", "explanation": "'include' は『含む』を意味します。" },
  { "q": "request", "choices": ["命令する", "約束する", "提案する", "要請する"], "answer": "要請する", "explanation": "'request' は『要請する』または『要請』を意味します。" },
  { "q": "contact", "choices": ["会議を開く", "紹介する", "連絡する", "訪問する"], "answer": "連絡する", "explanation": "'contact' は『連絡する』を意味します。" },
  { "q": "equipment", "choices": ["家具", "機器", "書類", "材料"], "answer": "機器", "explanation": "'equipment' は『機器』や『設備』を意味します（不可算名詞）。" },
  { "q": "attend", "choices": ["欠席する", "出席する", "準備する", "延期する"], "answer": "出席する", "explanation": "'attend' は『出席する』を意味します。" },
  { "q": "confirm", "choices": ["変更する", "提案する", "確認する", "疑う"], "answer": "確認する", "explanation": "'confirm' は『確認する』を意味します。" },
  { "q": "detail", "choices": ["概要", "詳細", "要点", "結論"], "answer": "詳細", "explanation": "'detail' は『詳細』を意味します。" },
  { "q": "cancel", "choices": ["延期する", "続ける", "取り消す", "予約する"], "answer": "取り消す", "explanation": "'cancel' は『取り消す』を意味します。" },
  { "q": "shipment", "choices": ["注文", "在庫", "支払い", "発送"], "answer": "発送", "explanation": "'shipment' は『発送』や『輸送貨物』を意味します。" },
  { "q": "delivery", "choices": ["配達", "集荷", "返品", "梱包"], "answer": "配達", "explanation": "'delivery' は『配達』を意味します。" },
  { "q": "schedule", "choices": ["記録", "規則", "予定", "結果"], "answer": "予定", "explanation": "'schedule' は『予定（表）』を意味します。" },
  { "q": "repair", "choices": ["破壊する", "交換する", "修理する", "設置する"], "answer": "修理する", "explanation": "'repair' は『修理する』または『修理』を意味します。" },
  { "q": "subject", "choices": ["市民", "物体", "科目", "主題"], "answer": "主題", "explanation": "文脈によりますが、Eメールなどでは『件名』や『主題』を意味します。" },
  { "q": "invoice", "choices": ["領収書", "見積書", "請求書", "注文書"], "answer": "請求書", "explanation": "'invoice' は『請求書』を意味します。" },
  { "q": "payment", "choices": ["割引", "支払い", "返金", "預金"], "answer": "支払い", "explanation": "'payment' は『支払い』を意味します。" },
  { "q": "due", "choices": ["無料の", "期限の", "利用可能な", "遅延した"], "answer": "期限の", "explanation": "'due' は『支払期限の』や『〜が原因で』を意味します。" },
  { "q": "charge", "choices": ["景品", "割引", "料金", "保証"], "answer": "料金", "explanation": "'charge' は『料金』や『請求』を意味します。" },
  { "q": "notice", "choices": ["記事", "通知", "噂", "広告"], "answer": "通知", "explanation": "'notice' は『通知』や『告知』、または『気づく』を意味します。" },
  { "q": "offer", "choices": ["質問", "拒否", "提供", "要求"], "answer": "提供", "explanation": "'offer' は『提供』や『申し出』、または『提供する』を意味します。" },
  { "q": "instead", "choices": ["特に", "一緒に", "代わりに", "直接"], "answer": "代わりに", "explanation": "'instead' は『代わりに』を意味します。" },
  { "q": "however", "choices": ["さらに", "したがって", "しかしながら", "例えば"], "answer": "しかしながら", "explanation": "'however' は『しかしながら』を意味します。" },
  { "q": "probably", "choices": ["確かに", "絶対に", "おそらく", "めったに〜ない"], "answer": "おそらく", "explanation": "'probably' は『おそらく』を意味します。" },
  { "q": "recently", "choices": ["常に", "以前に", "最近", "将来"], "answer": "最近", "explanation": "'recently' は『最近』を意味します。" },
  { "q": "especially", "choices": ["特に", "一般的に", "通常", "時々"], "answer": "特に", "explanation": "'especially' は『特に』を意味します。" },
  { "q": "several", "choices": ["多くの", "すべての", "少しの", "いくつかの"], "answer": "いくつかの", "explanation": "'several' は『いくつかの』を意味します。" },
  { "q": "join", "choices": ["見送る", "参加する", "去る", "断る"], "answer": "参加する", "explanation": "'join' は『参加する』を意味します。" },
  { "q": "prepare", "choices": ["開始する", "終える", "準備する", "忘れる"], "answer": "準備する", "explanation": "'prepare' は『準備する』を意味します。" },
  { "q": "remind", "choices": ["教える", "提案する", "忘れる", "思い出させる"], "answer": "思い出させる", "explanation": "'remind' は『思い出させる』を意味します。" },
  { "q": "able", "choices": ["〜する予定だ", "喜んで〜する", "できる", "できない"], "answer": "できる", "explanation": "'be able to'で『〜できる』を意味します。" },
  { "q": "possible", "choices": ["不可能な", "困難な", "可能な", "簡単な"], "answer": "可能な", "explanation": "'possible' は『可能な』を意味します。" },
  { "q": "necessary", "choices": ["不要な", "緊急の", "必要な", "任意の"], "answer": "必要な", "explanation": "'necessary' は『必要な』を意味します。" },
  { "q": "sure", "choices": ["心配して", "満足して", "不確かな", "確信して"], "answer": "確信して", "explanation": "'sure' は『確信して』を意味します。" },
  { "q": "both", "choices": ["どちらでもない", "どちらか一方", "両方", "すべて"], "answer": "両方", "explanation": "'both' は『両方』を意味します。" },
  { "q": "either", "choices": ["それぞれ", "どちらか一方", "両方", "どちらでもない"], "answer": "どちらか一方", "explanation": "'either' は『どちらか一方』を意味します。" },
  { "q": "another", "choices": ["最初の", "同じ", "もう一つの", "他のすべて"], "answer": "もう一つの", "explanation": "'another' は『もう一つの』を意味します。" },
  { "q": "each", "choices": ["多くの", "それぞれの", "いくつかの", "すべての"], "answer": "それぞれの", "explanation": "'each' は『それぞれの』を意味します。" },
  { "q": "while", "choices": ["〜する前に", "〜する間に", "〜した後で", "〜だけれども"], "answer": "〜する間に", "explanation": "'while' は『〜する間に』や『一方では』を意味します。" },
  { "q": "during", "choices": ["〜の後で", "〜なしで", "〜の前に", "〜の間に"], "answer": "〜の間に", "explanation": "'during' は特定の期間を示す『〜の間に』を意味します。" },
  { "q": "until", "choices": ["〜以来", "〜まで", "〜の時に", "〜の間に"], "answer": "〜まで", "explanation": "'until' は『〜まで（ずっと）』を意味します。" },
  { "q": "ago", "choices": ["〜後に", "〜前に", "〜以内に", "〜の間に"], "answer": "〜前に", "explanation": "'ago' は『〜前に』を意味し、過去形と共に使います。" },
  { "q": "already", "choices": ["ちょうど", "まだ", "すでに", "すぐに"], "answer": "すでに", "explanation": "'already' は『すでに』、『もう』を意味します。" },
  { "q": "yet", "choices": ["かつて", "ちょうど", "すでに", "まだ"], "answer": "まだ", "explanation": "否定文や疑問文で『まだ（〜ない）』を意味します。" },
  { "q": "still", "choices": ["かつて", "もはや", "ほとんど", "まだ"], "answer": "まだ", "explanation": "肯定文で『まだ』、『依然として』を意味します。" },
  { "q": "once", "choices": ["常に", "二度", "一度", "決して〜ない"], "answer": "一度", "explanation": "'once' は『一度』や『かつて』を意味します。" },
  { "q": "also", "choices": ["代わりに", "しかし", "また", "だから"], "answer": "また", "explanation": "'also' は『〜もまた』を意味します。" },
  { "q": "even", "choices": ["ほとんど", "〜だけ", "正確に", "〜でさえ"], "answer": "〜でさえ", "explanation": "'even' は『〜でさえ』を意味します。" },
  { "q": "enough", "choices": ["あまりに", "十分に", "全く", "ほとんど"], "answer": "十分に", "explanation": "'enough' は『十分に』を意味します。" },
  { "q": "quite", "choices": ["全く", "かなり", "少し", "ほとんど〜ない"], "answer": "かなり", "explanation": "'quite' は『かなり』や『まったく』を意味します。" },
  { "q": "almost", "choices": ["かろうじて", "正確に", "ほとんど", "完全に"], "answer": "ほとんど", "explanation": "'almost' は『ほとんど』を意味します。" },
  { "q": "abroad", "choices": ["地元へ", "都会へ", "海外へ", "国内へ"], "answer": "海外へ", "explanation": "'abroad' は『海外へ』や『海外で』を意味します。" },
  { "q": "finally", "choices": ["最初に", "ついに", "時々", "すぐに"], "answer": "ついに", "explanation": "'finally' は『ついに』や『最終的に』を意味します。" },
  { "q": "twice", "choices": ["何度も", "三度", "二度", "一度"], "answer": "二度", "explanation": "'twice' は『二度』や『二倍』を意味します。" },
  { "q": "usually", "choices": ["常に", "普段は", "めったに〜ない", "決して〜ない"], "answer": "普段は", "explanation": "'usually' は『普段は』や『たいてい』を意味します。" },
  { "q": "always", "choices": ["時々", "決して〜ない", "いつも", "めったに〜ない"], "answer": "いつも", "explanation": "'always' は『いつも』を意味します。" },
  { "q": "sometimes", "choices": ["めったに〜ない", "いつも", "時々", "決して〜ない"], "answer": "時々", "explanation": "'sometimes' は『時々』を意味します。" },
  { "q": "never", "choices": ["しばしば", "決して〜ない", "いつも", "時々"], "answer": "決して〜ない", "explanation": "'never' は『決して〜ない』を意味します。" },
  { "q": "often", "choices": ["めったに〜ない", "いつも", "時々", "しばしば"], "answer": "しばしば", "explanation": "'often' は『しばしば』を意味します。" },
  { "q": "together", "choices": ["一人で", "別々に", "一緒に", "交代で"], "answer": "一緒に", "explanation": "'together' は『一緒に』を意味します。" },
  { "q": "except", "choices": ["〜に加えて", "〜を含めて", "〜を除いて", "〜の代わりに"], "answer": "〜を除いて", "explanation": "'except' は『〜を除いて』を意味します。" },
  { "q": "without", "choices": ["〜にもかかわらず", "〜と共に", "〜なしで", "〜の代わりに"], "answer": "〜なしで", "explanation": "'without' は『〜なしで』を意味します。" },
  { "q": "through", "choices": ["〜の下に", "〜を横切って", "〜の上に", "〜を通して"], "answer": "〜を通して", "explanation": "'through' は『〜を通して』や『〜を通り抜けて』を意味します。" },
  { "q": "against", "choices": ["〜に沿って", "〜に賛成して", "〜に反対して", "〜に向かって"], "answer": "〜に反対して", "explanation": "'against' は『〜に反対して』や『〜に寄りかかって』を意味します。" },
  { "q": "among", "choices": ["〜の後ろに", "〜の上に", "〜のそばに", "〜の間で"], "answer": "〜の間で", "explanation": "3つ以上の『〜の間で』を意味します。" },
  { "q": "between", "choices": ["〜の間に", "〜の向こうに", "〜の周りに", "〜を通して"], "answer": "〜の間に", "explanation": "2つのものの『〜の間に』を意味します。" },
  { "q": "behind", "choices": ["〜の上に", "〜の隣に", "〜の後ろに", "〜の前に"], "answer": "〜の後ろに", "explanation": "'behind' は『〜の後ろに』を意味します。" },
  { "q": "below", "choices": ["〜の上に", "〜の下に", "〜の隣に", "〜の間に"], "answer": "〜の下に", "explanation": "'below' は『〜の下に』を意味します。" },
  { "q": "above", "choices": ["〜の周りに", "〜の下に", "〜の上に", "〜の向こうに"], "answer": "〜の上に", "explanation": "'above' は『〜の上に』を意味します。" },
  { "q": "near", "choices": ["〜から遠くに", "〜の外に", "〜の近くに", "〜の中に"], "answer": "〜の近くに", "explanation": "'near' は『〜の近くに』を意味します。" },
  { "q": "inside", "choices": ["〜の中に", "〜の外に", "〜の上に", "〜の下に"], "answer": "〜の中に", "explanation": "'inside' は『〜の中に』を意味します。" },
  { "q": "outside", "choices": ["〜の隣に", "〜の中に", "〜の向こうに", "〜の外に"], "answer": "〜の外に", "explanation": "'outside' は『〜の外に』を意味します。" },
  { "q": "across", "choices": ["〜に沿って", "〜の周りに", "〜を横切って", "〜を通して"], "answer": "〜を横切って", "explanation": "'across' は『〜を横切って』や『〜の向こう側に』を意味します。" },
  { "q": "far", "choices": ["近い", "狭い", "遠い", "広い"], "answer": "遠い", "explanation": "'far' は『遠い』を意味します。" },
  { "q": "full", "choices": ["空の", "小さい", "満杯の", "大きい"], "answer": "満杯の", "explanation": "'full' は『満杯の』を意味します。" },
  { "q": "empty", "choices": ["軽い", "空の", "満杯の", "重い"], "answer": "空の", "explanation": "'empty' は『空の』を意味します。" },
  { "q": "heavy", "choices": ["大きい", "軽い", "小さい", "重い"], "answer": "重い", "explanation": "'heavy' は『重い』を意味します。" },
  { "q": "light", "choices": ["明るい", "軽い", "暗い", "重い"], "answer": "軽い", "explanation": "'light' は『軽い』または『明るい』を意味します。" },
  { "q": "high", "choices": ["狭い", "高い", "低い", "広い"], "answer": "高い", "explanation": "'high' は『高い』を意味します。" },
  { "q": "low", "choices": ["遅い", "低い", "速い", "高い"], "answer": "低い", "explanation": "'low' は『低い』を意味します。" },
  { "q": "correct", "choices": ["簡単な", "間違った", "正しい", "難しい"], "answer": "正しい", "explanation": "'correct' は『正しい』を意味します。" },
  { "q": "wrong", "choices": ["良い", "間違った", "悪い", "正しい"], "answer": "間違った", "explanation": "'wrong' は『間違った』を意味します。" },
  { "q": "same", "choices": ["特別な", "同じ", "似ている", "違う"], "answer": "同じ", "explanation": "'same' は『同じ』を意味します。" },
  { "q": "different", "choices": ["珍しい", "同じ", "違う", "普通の"], "answer": "違う", "explanation": "'different' は『違う』を意味します。" },
  { "q": "easy", "choices": ["退屈な", "簡単な", "複雑な", "難しい"], "answer": "簡単な", "explanation": "'easy' は『簡単な』を意味します。" },
  { "q": "difficult", "choices": ["面白い", "難しい", "簡単な", "つまらない"], "answer": "難しい", "explanation": "'difficult' は『難しい』を意味します。" },
  { "q": "cheap", "choices": ["価値のある", "高価な", "無料の", "安い"], "answer": "安い", "explanation": "'cheap' は『安い』を意味します。" },
  { "q": "expensive", "choices": ["手頃な", "高価な", "安い", "価値のない"], "answer": "高価な", "explanation": "'expensive' は『高価な』を意味します。" },
  { "q": "famous", "choices": ["人気のある", "無名な", "有名な", "珍しい"], "answer": "有名な", "explanation": "'famous' は『有名な』を意味します。" },
  { "q": "popular", "choices": ["不人気な", "人気のある", "一般的な", "特別な"], "answer": "人気のある", "explanation": "'popular' は『人気のある』を意味します。" },
  { "q": "public", "choices": ["公共の", "私的な", "個人の", "秘密の"], "answer": "公共の", "explanation": "'public' は『公共の』や『一般の』を意味します。" },
  { "q": "private", "choices": ["会社の", "私的な", "公共の", "政府の"], "answer": "私的な", "explanation": "'private' は『私的な』や『個人の』を意味します。" }
];
